apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-mongodb-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName:  default
